import type { FinalClause } from "@/lib/types";

// Pre-baked analysis of Uber Driver Agreement (public document)
// Used as instant fallback if live API is unavailable during demo
export const DEMO_CLAUSES: FinalClause[] = [
  {
    id: 1,
    text: "By entering into this Agreement, you grant Uber a worldwide, perpetual, irrevocable, royalty-free license to use, reproduce, modify, adapt, publish, translate, distribute, and display any content you provide through the Platform.",
    type: "IP_Transfer",
    section: "Section 4 — Intellectual Property",
    severity: "HIGH",
    risk_summary: "You permanently give up rights to everything you submit — photos, reviews, feedback — forever.",
    legal_reasoning: "A perpetual, irrevocable license is effectively a permanent transfer of economic value without compensation. Under 17 U.S.C. §101, standard platform licenses limit scope to 'necessary for platform operation' and include a termination right.",
    category_flags: ["ip_risk", "financial_risk"],
    what_it_costs_you: "If you sign this, you lose all rights to any content you create — including photos, performance data, and reviews — with no ability to revoke or receive compensation, even after leaving the platform.",
    push_back: "Ask them to change 'perpetual, irrevocable' to 'for the duration of your active driver account, terminable by either party with 30 days notice' and add 'solely for the purpose of operating and improving the Platform.'",
    red_flag_label: "Unlimited IP Grab",
  },
  {
    id: 2,
    text: "Any dispute shall be determined by arbitration. You waive your right to a jury trial and to participate in a class action lawsuit.",
    type: "Arbitration",
    section: "Section 15 — Dispute Resolution",
    severity: "HIGH",
    risk_summary: "You give up your right to sue in court and join a class action — disputes go to private arbitration instead.",
    legal_reasoning: "The EFAA (Ending Forced Arbitration Act, 2022) bars mandatory arbitration for sexual harassment and assault claims. Under Epic Systems v. Lewis (2018), class action waivers are enforceable, meaning you cannot join collective suits over wage theft or misclassification.",
    category_flags: ["employment_risk", "financial_risk"],
    what_it_costs_you: "If you sign this, you lose the right to sue Uber in court or join other drivers in a class action — even for systematic underpayment. Private arbitration strongly favors the repeat player.",
    push_back: "Ask them to remove the class action waiver entirely, or add a carve-out for statutory wage and labor claims. At minimum, request that all arbitration costs be borne entirely by Uber.",
    red_flag_label: "Forced Arbitration",
  },
  {
    id: 3,
    text: "Uber may collect location data from your device continuously during an active trip and for 5 minutes after completion. Uber may also collect location data at intervals while the app is running in the background.",
    type: "Data_Privacy",
    section: "Section 9 — Data Collection",
    severity: "HIGH",
    risk_summary: "Uber tracks your location constantly — even when you're not driving — with vague justifications.",
    legal_reasoning: "Continuous background location tracking without clear opt-out likely exceeds what GDPR Article 6 allows (requires lawful basis, limited to stated purpose). Under CCPA §1798.100, you have the right to know what data is collected.",
    category_flags: ["privacy_risk"],
    what_it_costs_you: "If you sign this, Uber can track your location at all times the app is installed — including personal trips, your home location, and off-platform movements — with no clear retention limit.",
    push_back: "Ask them to limit background location collection to when you are actively logged into driver mode and commit to a data retention limit of 90 days with a clear opt-out.",
    red_flag_label: "Always-On Tracking",
  },
  {
    id: 4,
    text: "Uber reserves the right to deactivate your account, with or without cause, at any time and without prior notice. Uber's decision to deactivate your account is final and not subject to appeal.",
    type: "Termination",
    section: "Section 12 — Account Deactivation",
    severity: "HIGH",
    risk_summary: "Uber can shut down your entire income source instantly, without explanation, with no appeal.",
    legal_reasoning: "A termination clause with no cause, no notice, and no appeal removes all procedural protection. Courts in some jurisdictions apply the implied covenant of good faith even to independent contractor agreements. The 'final and not subject to appeal' language removes any recourse.",
    category_flags: ["employment_risk", "financial_risk"],
    what_it_costs_you: "If you sign this, Uber can permanently eliminate your income overnight with no reason given and no path to reinstatement — leaving you with no legal recourse and no severance.",
    push_back: "Ask them to add: (1) 14 days written notice for deactivation except in verified safety violations, (2) a written statement of the reason, and (3) a one-time appeal process with response within 7 business days.",
    red_flag_label: "No Exit Clause",
  },
  {
    id: 5,
    text: "You shall not, during this Agreement and for 12 months thereafter, provide rideshare or delivery services through any competing platform within any metropolitan area where you have completed Uber trips.",
    type: "Non_Compete",
    section: "Section 7 — Restrictive Covenants",
    severity: "HIGH",
    risk_summary: "You can't drive for Lyft, DoorDash, or any competitor for a full year after leaving Uber.",
    legal_reasoning: "This non-compete is unenforceable in California under Labor Code §925. The FTC's 2024 guidance signals federal movement toward banning most non-competes. For independent contractors, broad geographic non-competes are increasingly void as contrary to public policy.",
    category_flags: ["employment_risk", "freedom_risk"],
    what_it_costs_you: "If you sign this, you lose the ability to work on any competing gig platform for an entire year — effectively making you economically dependent on Uber with no income fallback.",
    push_back: "Ask them to delete this clause entirely — non-competes for independent contractors are unenforceable in California (Labor Code §925). If they insist, demand it be limited to 30 days and your immediate city only.",
    red_flag_label: "1-Year Non-Compete",
  },
  {
    id: 6,
    text: "Uber may modify the fee structure and service fees at any time with 30 days notice by email. Continued use of the platform constitutes acceptance of the modified terms.",
    type: "Payment",
    section: "Section 6 — Compensation",
    severity: "MEDIUM",
    risk_summary: "Uber can cut your pay with only 30 days notice — your only option is to quit.",
    legal_reasoning: "Unilateral modification clauses are generally enforceable under contract law. 30 days notice is below the industry standard of 60 days for material payment changes. The absence of a minimum rate floor is the core risk.",
    category_flags: ["financial_risk"],
  },
  {
    id: 7,
    text: "You agree to maintain commercial auto insurance with minimum coverage of $1,000,000 per occurrence while using the Platform. Uber's insurance applies only during active trip periods.",
    type: "Liability",
    section: "Section 8 — Insurance",
    severity: "MEDIUM",
    risk_summary: "You bear the full insurance cost, and Uber's coverage only applies during narrow active-trip windows.",
    legal_reasoning: "Personal auto policies typically exclude commercial use. The gap between app-on/waiting and actively carrying a passenger creates an insurance gray zone that can cost $2,400–4,800/yr in additional premiums falling entirely on you.",
    category_flags: ["financial_risk"],
  },
  {
    id: 8,
    text: "You acknowledge that you are an independent contractor and not an employee. You are not entitled to employee benefits including health insurance, workers' compensation, or paid leave.",
    type: "Other",
    section: "Section 2 — Independent Contractor",
    severity: "MEDIUM",
    risk_summary: "The contractor classification denies you employee protections — and this designation is legally contested.",
    legal_reasoning: "Independent contractor classification in gig work is actively challenged. California's AB5 ABC test, Massachusetts's similar standard, and the DOL's 2024 guidance all signal that platform workers may qualify as employees. This agreement cannot override statutory classification.",
    category_flags: ["employment_risk"],
  },
  {
    id: 9,
    text: "You agree not to make public statements or post content that disparages or reflects negatively on Uber, its officers, directors, employees, or business partners.",
    type: "NDA",
    section: "Section 11 — Non-Disparagement",
    severity: "MEDIUM",
    risk_summary: "You can't publicly criticize Uber — this may conflict with your right to discuss working conditions.",
    legal_reasoning: "Broad non-disparagement clauses have been challenged under NLRA §7, which protects workers' rights to engage in concerted activity including public complaints about working conditions. The NLRB has found broad clauses unlawful in employment contexts.",
    category_flags: ["freedom_risk"],
  },
  {
    id: 10,
    text: "This Agreement constitutes the entire agreement between the parties and supersedes all prior agreements, representations, warranties, and understandings.",
    type: "Other",
    section: "Section 18 — General Provisions",
    severity: "LOW",
    risk_summary: "Standard entire-agreement clause — this document overrides any verbal promises made to you.",
    legal_reasoning: "Merger clauses are standard and routinely enforced. Any verbal representations made during onboarding (e.g., 'you'll earn at least $X/hour') are unenforceable unless written into this agreement.",
    category_flags: [],
  },
];

export const DEMO_META = {
  fileName: "uber-driver-agreement.pdf",
  source: "Uber Driver Terms of Service (public document)",
};
